---
sidebar: sidebar 
permalink: oci/add-credentials-oci.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials, oci nss, oracle cloud infrastructure 
summary: 添加 Oracle Cloud Infrastructure（OCI）凭据，以便 Workload Factory 拥有在 OCI 帐户中部署和管理云资源所需的权限。 
---
= 将 Oracle Cloud Infrastructure 凭据添加到 NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
添加和管理云提供商凭据，以便 NetApp Workload Factory 拥有部署和管理云提供商帐户中的资源所需的权限。

link:permissions-oci.html["OCI NetApp 存储服务的权限"]

.关于此任务
您可以从“凭据”页面向现有 Workload Factory 帐户添加凭据。这为 Workload Factory 提供了在云环境中管理资源和流程所需的权限。

.开始之前
您需要有凭据才能登录到您的 Oracle Cloud Infrastructure 帐户。

.步骤
. 登录到 https://console.netapp.com/["NetApp 控制台"^]。
. 从菜单中，选择 *Workloads* > *Administration* > *Credentials*。
. 在“凭据”页面上，选择*添加凭据*。
. 在添加 Oracle Cloud Infrastructure NetApp 存储服务凭据页面上，执行以下操作：
+
.. 在 _权限配置_ 下，为 Oracle Cloud Infrastructure NetApp Storage Service 凭据选择适当的权限。*查看、计划和分析* 权限是默认设置。此权限策略允许您查看 OCI NSS 存储池，了解系统运行状况，获取系统的架构完善的分析，并探索节省方案。
.. 请按照使用 Oracle Cloud Console 提供的手动步骤完成 OCI NSS 凭据的权限配置。
.. 在_凭据名称_下，输入要用于这些凭据的名称，然后输入租户 OCID。


. 选择 *Add*。


.下一步
link:quick-start-oci.html["NetApp Workload Factory 中的 Oracle 云基础架构 NetApp 存储服务快速入门。"]
