---
sidebar: sidebar 
permalink: gcnv/add-credentials.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials 
summary: 添加 Google Cloud NetApp Volumes 凭据，以便 Workload Factory 拥有在您的 Google 帐户中部署和管理云资源所需的权限。 
---
= 将 Google Cloud NetApp Volumes 凭据添加到 NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
添加和管理云提供商凭据，以便 NetApp Workload Factory 拥有部署和管理云提供商帐户中的资源所需的权限。



[[overview]]
== 概述

您可以从 NetApp 控制台的“凭据”页面添加 Google Cloud NetApp Volumes 凭据。控制台提供引导式设置说明和文档链接，因此您可以完成所需的 Google Cloud 配置，然后返回完成添加凭据。

使用此工作流程可授予 Workload Factory 在 Google Cloud 环境中发现、分析和管理资源所需的权限。

创建凭据分为三个部分：

* 步骤 1：选择要授予 Workload Factory 的权限级别。
* 第 2 步：创建并验证 Google Cloud 服务帐户，然后选择要管理的 Google Cloud 项目。
* 步骤 3：输入凭据名称并添加凭据。


.开始之前
您需要有凭据才能登录到 Google Cloud 帐户。

.步骤
. 登录到 https://console.netapp.com/["NetApp 控制台"^]。
. 从菜单中，选择 *Workloads* > *Administration* > *Credentials*。
. 在“凭据”页面上，选择*添加凭据*。
. 选择 *Google Cloud NetApp Volumes* 作为云提供商。
. 在添加 Google Cloud NetApp Volumes 凭据页面上，完成*权限配置*下的每个部分。




[[step-1-create-permission-policies]]
=== 步骤 1：创建权限策略

.步骤
. 在*创建权限策略*下，默认选择*查看、计划和分析*。通过此权限策略，您可以查看 Google Cloud NetApp Volumes 存储池，了解系统健康状况，为您的系统获取精心设计的分析，并探索节省费用的方法。
. 可选：如果您还希望 Workload Factory 管理 Google Cloud NetApp Volumes 资源并修复配置问题，请选择 *操作和修复*。
. 在继续操作之前，请查看 link:https://docs.netapp.com/us-en/storage-management-google-cloud-netapp-volumes/task-set-up-gcnv.html#set-up-a-service-account["设置 Google Cloud NetApp Volumes"^] 中的设置说明。




[[step-2-create-the-google-cloud-service-account]]
=== 步骤 2：创建 Google Cloud 服务帐户

.步骤
. 展开*设置 Google Cloud 环境*。
. 完成显示的步骤 1-5，以创建 Google Cloud 服务帐户。
. 复制服务帐户电子邮件地址。
. 返回 Workload Factory，将电子邮件地址粘贴到 *GCP 服务帐户* 字段中，然后选择 *验证凭据*。
. 验证完成后，从*项目*下拉列表中，选择您希望 Workload Factory 管理的 Google Cloud 项目。注意：在验证服务帐户凭据之前，项目列表不可用。




[[step-3-enter-the-credentials-name]]
=== 步骤 3：输入凭据名称

.步骤
. 展开*凭据名称*。
. 在 *名称* 字段中，输入仅使用字母数字字符的凭据名称。不允许使用特殊字符和空格。
. 选择 *Add*。


.结果
Google Cloud NetApp Volumes 凭据将添加到您的帐户中，并可用于支持的 Workload Factory 操作。
