---
sidebar: sidebar 
permalink: fsx-vmware/deploy-fsx-file-system-evs.html 
keywords: vm workloads, deploy fsx, deploy storage for vms, evs, elastic vmware service 
summary: 在您验证推荐的 FSx for ONTAP 文件系统（在某些情况下为多个文件系统）完全符合您的要求后，您可以使用 Workload Factory 在您的 AWS 环境中部署该系统。 
---
= 部署建议的 FSx for ONTAP 文件系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在验证推荐的 FSx for ONTAP 文件系统（或在某些情况下为多个文件系统）符合您的确切要求后，您可以使用 Workload Factory 在您的 AWS 环境中部署该系统。

根据添加到 Workload Factory 帐户的策略和权限，您可以使用 Workload Factory（使用读/写模式）完全部署 FSx for ONTAP 文件系统。如果您的权限较少（只读模式）或没有权限（基本模式），则需要使用 Codebox 中的 CloudFormation 模板，并在 AWS 中自行部署 FSx for ONTAP 文件系统。



[[requirements]]
== 要求

* 您必须具有 Amazon Elastic VMware Service 订阅。
* 您必须具有必要的权限，才能在您的 AWS 帐户中创建 FSx for ONTAP 文件系统。




[[considerations]]
== 注意事项

* 您可以使用“快速创建”或“高级创建”选项。高级创建提供了一些额外的存储参数，您可以自定义这些参数。link:../fsx-storage/create-discover-systems.html["了解这两种选择可以带来哪些好处"]。
* 在“Amazon Elastic VMware Service 首选项”部分，您可以选择 EVS 虚拟化环境连接到外部数据存储。这将使用部署的最佳实践选项自动填充某些字段。您可以根据需要更改这些选项。




[[steps]]
== 步骤

. 在*查看计划*页面的底部，选择*部署*，将显示创建 FSx for ONTAP 文件系统页面。
+
定义您的 FSx for ONTAP 文件系统的大多数字段都是根据您提供的信息填写的，但您需要在此页面中填写一些字段。

. 在“文件系统常规配置”部分中，输入以下信息：
+
.. *AWS凭据*：选择或添加凭据，以授予 Workload Factory 直接创建 FSx for ONTAP 文件系统所需的权限。您还可以从 Codebox 中选择 CloudFormation 代码，并在 AWS 中自行部署 FSx for ONTAP 文件系统。
.. *文件系统名称*：输入要用于此 FSx for ONTAP 文件系统的名称。
.. *标签*：您可以选择添加标签来对该 FSx for ONTAP 文件系统进行分类。


. 在“Amazon Elastic VMware Service 首选项”部分的“环境 ID”列表中，选择将连接数据存储的 EVS 环境。
+
这将自动填充以下字段：

+
** *VPC*
** *可用区*
** *子网*
** 在 *NFS 数据存储访问* 部分，如果您选择了 *仅 EVS 主机管理* 选项，则会自动填充 *EVS 主机管理（CIDR）* 字段。
** 在*数据存储区挂载选项*部分，如果您选择将数据存储区挂载到 EVS 集群，则会自动填充 *EVS 集群 VMware vCenter 地址* 和 *vSphere 管理员凭据密钥 ARN* 字段。


. 在“网络与安全”部分中，输入以下信息：
+
.. *区域和 VPC*：选择将部署 FSx for ONTAP 文件系统的区域和 VPC。
.. *安全组*（仅限高级创建）：使用*高级创建*选项时，您可以为 FSx for ONTAP VPC 选择默认安全组，以便所有流量都可以访问 FSx for ONTAP 文件系统。您可以创建新的安全组，也可以选择现有的安全组。
+
如果启用*将安全组配置调整为 EVS NFS 数据存储*选项，Workload Factory 会根据 EVS NFS 数据存储的设置配置安全组。

+
您可以向安全组添加入站规则，以限制哪些其他 AWS 服务可以访问 FSx for ONTAP 文件系统。这将减少开放的服务数量。以下是所需的最低端口和协议：

+
[cols="15,10,55"]
|===
| 协议 | 端口 | 目的 


| TCP、UDP | 111 | Portmapper（用于协商 NFS 请求中使用的端口） 


| TCP、UDP | 635 | NFS mountd （接收 NFS 挂载请求） 


| TCP、UDP | 2049 | NFS 网络流量 


| TCP、UDP | 4045 | Network Lock Manager (NLM, lockd) - 处理锁定请求。 


| TCP、UDP | 4046 | 网络状态监视器（NSM, statd）- 通知 NFS 客户端服务器重新启动，以便进行锁定管理。 
|===
.. *可用区*：选择可用区和子网。
+
如果要避免跨 AZ 流量收费，则应选择与 VMware SDDC 部署位置相同的可用区。

.. *加密*（仅限高级创建）：使用*高级创建*选项时，您可以从下拉列表中选择 AWS 加密密钥名称。
.. *NFS 数据存储访问*（仅限高级创建）：使用*高级创建*选项时，您可以选择是否所有主机都可以访问数据存储，或者是否只有 EVS 管理主机才能访问数据存储。


. 在“文件系统详细信息”部分中，输入以下信息：
+
.. *ONTAP 凭据*：输入 ONTAP 用户名密码。
.. *存储虚拟机凭据*（仅限高级创建）：输入并确认存储虚拟机密码。密码可以特定于此文件系统，也可以使用为 ONTAP 凭据输入的相同密码。


. 在“EVS 集群附加”部分中，输入以下信息：
+
.. *数据存储区挂载选项*：（可选）启用*将数据存储区挂载到 EVS 群集*选项，以自动将数据存储区连接到 Amazon EVS 群集。此选项还会使 Workload Factory 配置 VMware ESXi 主机设置，使其与 ONTAP 最佳实践建议相匹配。在部署文件系统之前，您可以在*摘要*部分查看计划详细信息，以查看已更改的设置。
.. *EVS 集群 vSphere 控制台详细信息*：输入应连接到 Amazon EVS 的 VMware vCenter 服务器的 IP 地址或 FQDN。
.. *vSphere 管理员凭据密钥 ARN*：选择 vSphere 管理员凭据的密钥 ARN。这些凭据用于挂载数据存储并配置推荐的 VMware 设置。
+
如果此区域不提供 Amazon EVS，或者您的帐户无权检索可用机密 ARN 列表，您可以手动输入机密 ARN 值。



. 在 *摘要* 部分，您可以查看 VMware 迁移顾问根据您的信息设计的 FSx for ONTAP 文件系统和数据存储配置。
. 选择 *创建* 以部署 FSx for ONTAP 文件系统。此过程最多可能需要 2 小时。
+
（可选）在 Codebox 窗口中，您可以选择 *重定向到 CloudFormation* 以使用 CloudFormation 堆栈创建文件系统和推荐的虚拟机配置。

+
无论哪种情况，您都可以在 CloudFormation 中监控创建进度。





[[result]]
== 结果

FSx for ONTAP 文件系统已部署。您现在可以使用 Codebox 中的 AWS CloudFormation 模板将推荐的虚拟机配置部署到您的 Amazon Elastic VMware Service 环境中。
