---
sidebar: sidebar 
permalink: fsx-vmware/deploy-fsx-file-system.html 
keywords: vm workloads, deploy fsx, deploy storage for vms 
summary: 在您验证推荐的 FSx for ONTAP 文件系统（在某些情况下为多个文件系统）完全符合您的要求后，您可以使用 Workload Factory 在您的 AWS 环境中部署该系统。 
---
= 部署建议的 FSx for ONTAP 文件系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在验证推荐的 FSx for ONTAP 文件系统（或在某些情况下为多个文件系统）符合您的确切要求后，您可以使用 Workload Factory 在您的 AWS 环境中部署该系统。

根据添加到 Workload Factory 帐户的策略和权限，您可以使用 Workload Factory（使用读/写模式）完全部署 FSx for ONTAP 文件系统。如果您的权限较少（只读模式）或没有权限（基本模式），则需要使用 Codebox 中的 CloudFormation 信息，并在 AWS 中自行部署 FSx for ONTAP 文件系统。

.部署到 VMware Cloud on AWS 的要求
* 您必须使用 VMware Cloud on AWS 软件定义数据中心（SDDC）1.20 或更高版本才能部署 FSx for ONTAP 文件系统。
* 您不得在 SDDC 部署期间使用的同一 VPC 中部署 FSx for ONTAP 文件系统。相反，您必须将其部署在您拥有的新 Amazon VPC 中，以实现 VMware Cloud on AWS 与 Amazon FSx for NetApp ONTAP 的集成。
* 您必须在与 SDDC 相同的 AWS 区域中部署 FSx for ONTAP 文件系统。


.步骤
. 在*查看计划*页面的底部，选择*部署*，将显示创建 FSx for ONTAP 文件系统页面。
+
定义您的 FSx for ONTAP 文件系统的大多数字段都是根据您提供的信息填写的，但您需要在此页面中填写一些字段。

+
您可以使用“快速创建”或“高级创建”选项。高级创建提供了一些额外的存储参数，您可以自定义这些参数。link:../fsx-storage/create-discover-systems.html["了解这两种选择可以带来哪些好处"]。

. *AWS凭据*：选择或添加凭据，以授予 Workload Factory 直接创建 FSx for ONTAP 文件系统所需的权限。您还可以从 Codebox 中选择 CloudFormation 代码，并在 AWS 中自行部署 FSx for ONTAP 文件系统。
. *文件系统名称*：输入要用于此 FSx for ONTAP 文件系统的名称。
. *标签*：您可以选择添加标签来对此 FSx for ONTAP 文件系统进行分类。
. 在“网络与安全”部分中，输入以下信息：
+
.. *区域和 VPC*：选择将部署 FSx for ONTAP 文件系统的区域和 VPC。
+
如果要部署到 VMware Cloud on AWS，请确保将其部署在与部署 VMware Cloud on AWS 的 VPC 不同的 VPC 中。

.. *安全组*：使用*高级创建*选项时，您可以为 FSx for ONTAP VPC 选择默认安全组，以便所有流量都可以访问 FSx for ONTAP 文件系统。
+
您可以添加入站规则，限制其他 AWS 服务访问 FSx for ONTAP 文件系统。这将限制开放的服务数量。以下是最低要求的端口和协议：

+
[cols="15,10,55"]
|===
| 协议 | 端口 | 目的 


| TCP、UDP | 111 | Portmapper（用于协商 NFS 请求中使用的端口） 


| TCP、UDP | 635 | NFS mountd （接收 NFS 挂载请求） 


| TCP、UDP | 2049 | NFS 网络流量 


| TCP、UDP | 4045 | Network Lock Manager (NLM, lockd) - 处理锁定请求。 


| TCP、UDP | 4046 | 网络状态监视器（NSM, statd）- 通知 NFS 客户端服务器重新启动，以便进行锁定管理。 
|===
.. *可用区*：选择可用区和子网。
+
如果要避免跨 AZ 流量收费，则应选择与 VMware SDDC 部署位置相同的可用区。

.. *加密*：使用*高级创建*选项时，您可以从下拉列表中选择 AWS 加密密钥名称。
.. *数据存储访问控制*：使用*高级创建*选项时，您可以选择是否所有主机都可以访问数据存储，或者是否只有特定子网上的某些 vSphere 群集节点才能访问数据存储。


. 在“文件系统详细信息”部分中，输入以下信息：
+
.. *ONTAP 凭据*：输入并确认 ONTAP 密码。
.. *存储虚拟机凭据*（仅限高级创建）：输入并确认存储虚拟机密码。密码可以特定于此文件系统，也可以使用为 ONTAP 凭据输入的相同密码。


. 在 *摘要* 部分，您可以查看 VMware 迁移顾问根据您的信息设计的 FSx for ONTAP 文件系统和数据存储配置。
. 选择 *创建* 以部署 FSx for ONTAP 文件系统。此过程最多可能需要 2 小时。
+
（可选）在 Codebox 窗口中，您可以选择 *重定向到 CloudFormation* 以使用 CloudFormation 堆栈创建文件系统。

+
无论哪种情况，您都可以在 CloudFormation 中监控创建进度。



.结果
FSx for ONTAP 文件系统已部署。
