---
sidebar: sidebar 
permalink: setup/learn-about-permissions.html 
keywords: permissions, actions 
summary: 要使用 NetApp Workload Factory 功能和服务，您需要提供权限，以便 Workload Factory 可以在您的云环境中执行操作。 
---
= NetApp Workload Factory 的权限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要使用 NetApp Workload Factory 功能和服务，您需要提供权限，以便 Workload Factory 可以在您的云环境中执行操作。



[[why-use-permissions]]
== 为什么要使用权限

当您提供权限时，Workload Factory 会将策略附加到实例，以提供管理您的云提供商帐户内的资源和流程的权限。这使得 Workload Factory 能够执行各种操作，从发现您的存储环境到在存储管理中部署云资源（如卷）。

例如，对于 FSx for ONTAP 数据库工作负载，当 Workload Factory 被授予所需的权限时，它将扫描给定帐户和区域中的所有 EC2 实例，并筛选所有基于 Windows 的计算机。如果已在主机上安装并运行 AWS Systems Manager (SSM) Agent，并且正确配置了 System Manager 网络，则 Workload Factory 可以访问 Windows 计算机并验证是否已安装 SQL Server 软件。



[[how-permissions-are-used]]
== 权限的使用方式

Workload Factory 使用权限来执行某些任务。权限捆绑到设定的权限策略中。权限策略显示在 link:../admin/codebox-automation.html["Codebox"] 中，并且是可复制的 JSON。每个云提供商都有自己的权限策略集，可根据该云环境的特定要求和功能进行定制。本文档提供每个云提供商的权限参考。



[[permission-references-by-cloud-provider]]
=== 云提供商的权限引用

请参阅以下页面以了解云提供商的权限要求：

* link:../fsx-storage/permissions-reference-fsx.html["Amazon FSx for NetApp ONTAP"]
* link:../oci/permissions-oci.html["OCI NetApp 存储服务"]

